'no':
  helpers:
    models:
      group:
        one: "gjeng"
        other: "gjenger"
        save_error: "En feil skjedde under laglring."
